---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Updating apt
      command: sudo apt-get update

    - name: Install Docker
      command: sudo apt-get install -y docker.io
      become: yes
      become_user: root

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
      become_user: root

  handlers:
    - name: Restart Docker Service
      systemd:
        name: docker
        state: restarted
      become: yes
      become_user: root

- name: Deploy Docker Container
  hosts: your_target_host
  tasks:
    - name: Run Docker Container
      become: yes
      become_user: root
      shell: docker run -itd -p 8086:8081 sivaops7/finance-me:1.0

    - name: Stop Docker container
      community.general.docker_container:
        name: sivaops7/finance-me
        state: stopped
      notify: Restart Docker Service

